dsn: cockroach://root@${AUTHE_DB_ADDRESS:-authe-db:22000}/defaultdb?sslmode=disable

serve:
  public:
    port: ${AUTHE_PORT:-23000}
    base_url: ${AUTHE_WEBAUTH_PUBLIC_URL:-http://localhost:21000}/api
  admin:
    port: ${AUTHE_ADMIN_PORT:-23001}

identity:
  default_schema_id: user
  schemas:
    - id: user
      url: file://./conf/user.schema.json

selfservice:
  default_browser_return_url: ${AUTHE_WEBAUTH_PUBLIC_URL:-http://localhost:21000}/success
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
  flows:
    login:
      ui_url: ${AUTHE_WEBAUTH_PUBLIC_URL:-http://localhost:21000}/login
    registration:
      ui_url: ${AUTHE_WEBAUTH_PUBLIC_URL:-http://localhost:21000}/register
    error:
      ui_url: ${AUTHE_WEBAUTH_PUBLIC_URL:-http://localhost:21000}/error
    settings:
      ui_url: ${AUTHE_WEBAUTH_PUBLIC_URL:-http://localhost:21000}/settings

courier:
  smtp:
    connection_uri: smtps://foo:bar@0.0.0.0:0/
