dsn: cockroach://authe@${AUTHE_DB_ADDRESS:-authe-db:22000}/database?password=${AUTHE_DB_PASSWORD:-password}&sslmode=verify-full&sslrootcert=/etc/certs/ca.pem&sslcert=/etc/certs/client.cert.pem&sslkey=/etc/certs/client.key.pem

cookies:
  domain: ${AUTHE_COOKIE_DOMAIN:-localhost}

session:
  cookie:
    domain: ${AUTHE_COOKIE_DOMAIN:-localhost}

serve:
  public:
    port: ${AUTHE_PORT:-23000}
    base_url: ${AUTHE_AUTHGATE_PUBLIC_URL:-https://localhost:20000}/authe
    tls:
      cert:
        path: /etc/certs/cert.pem
      key:
        path: /etc/certs/key.pem
  admin:
    port: ${AUTHE_ADMIN_PORT:-23001}
    base_url: ${AUTHE_ADMIN_PUBLIC_URL:-https://localhost:23001}
    tls:
      cert:
        path: /etc/certs/cert.pem
      key:
        path: /etc/certs/key.pem

identity:
  default_schema_id: user
  schemas:
    - id: user
      url: file://./conf/user.schema.json

selfservice:
  default_browser_return_url: ${AUTHE_AUTHGATE_PUBLIC_URL:-https://localhost:20000}/ui
  methods:
    link:
      enabled: true
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
  flows:
    error:
      ui_url: ${AUTHE_AUTHGATE_PUBLIC_URL:-https://localhost:20000}/ui/error
    login:
      ui_url: ${AUTHE_AUTHGATE_PUBLIC_URL:-https://localhost:20000}/ui/login
    recovery:
      enabled: true
      ui_url: ${AUTHE_AUTHGATE_PUBLIC_URL:-https://localhost:20000}/ui/recover
    registration:
      enabled: false
    settings:
      ui_url: ${AUTHE_AUTHGATE_PUBLIC_URL:-https://localhost:20000}/ui/settings
    verification:
      enabled: false

courier:
  smtp:
    connection_uri: smtps://foo:bar@0.0.0.0:0/
